# Generated by Django 2.2.7 on 2019-11-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=80)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
